services:
  - type: web
    name: weddink
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app 
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: APIFY_API_TOKEN
        sync: false
      - key: PORT
        value: 5000
    disk:
      name: weddink-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    autoDeploy: true
